DowConstituents = [{"label":"UnitedHealth","value":"UNH"},
{"label":"Goldman Sachs","value":"GS"},
{"label":"Home Depot","value":"HD"},
{"label":"Microsoft","value":"MSFT"},
{"label":"McDonald's","value":"MCD"},
{"label":"Amgen","value":"AMGN"},
{"label":"Caterpillar","value":"CAT"},
{"label":"Visa","value":"V"},
{"label":"Honeywell","value":"HON"},
{"label":"Johnson & Johnson","value":"JNJ"},
{"label":"American Express","value":"AXP"},
{"label":"Boeing","value":"BA"},
{"label":"Salesforce","value":"CRM"},
{"label":"Travelers","value":"TRV"},
{"label":"Apple","value":"AAPL"},
{"label":"Procter & Gamble","value":"PG"},
{"label":"Chevron","value":"CVX"},
{"label":"Walmart","value":"WMT"},
{"label":"3M","value":"MMM"},
{"label":"IBM","value":"IBM"},
{"label":"Nike","value":"NKE"},
{"label":"JPMorgan Chase","value":"JPM"},
{"label":"Disney","value":"DIS"},
{"label":"Merck","value":"MRK"},
{"label":"Dow","value":"DOW"},
{"label":"Coca-Cola","value":"KO"},
{"label":"Cisco","value":"CSCO"},
{"label":"Verizon","value":"VZ"},
{"label":"Intel","value":"INTC"},
{"label":"Walgreens Boots Alliance","value":"WBA"}]

Intervals = [
    {"label":"5 Minutes", "yahooterm": "5m","yahooperiod":"60d"},
    {"label":"30 Minutes", "yahooterm": "30m", "yahooperiod": "60d"},
    {"label":"1 Hour", "yahooterm":"1h","yahooperiod":"730d"},
    {"label":"1 Day", "yahooterm":"1d", "yahooperiod":"10y"},
]
